# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oui < Formula
  desc "MAC Address CLI Toolkit"
  homepage "https://github.com/thatmattlove/oui"
  version "2.0.3"
  license "BSD-3-Clause-Clear"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thatmattlove/oui/releases/download/v2.0.3/oui_2.0.3_darwin_arm64.tar.gz"
      sha256 "0837e64554be1f7932743ffe37b851d31c149764825237d7bb8e037fb88c100e"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/oui/releases/download/v2.0.3/oui_2.0.3_darwin_amd64.tar.gz"
      sha256 "1bd270b077a33a6334cc5654efd5f90b7a1283a1c6de9d46b247cacc5f9d8a54"

      def install
        bin.install "oui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/oui/releases/download/v2.0.3/oui_2.0.3_linux_armv6.tar.gz"
      sha256 "cb1f9928b2d801186e77042bc77f14ee8e0f54e0d411e579cdf20cfef719cf43"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/oui/releases/download/v2.0.3/oui_2.0.3_linux_amd64.tar.gz"
      sha256 "bb7ef8853fac8744cc6d5c972ef6c0998c48b9f041e6274df9c9a8c2af6363bf"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/oui/releases/download/v2.0.3/oui_2.0.3_linux_arm64.tar.gz"
      sha256 "c7cd3ae7351117a49d2d2674bbe174aac030b953b18adfc29ec08c87716a8ad1"

      def install
        bin.install "oui"
      end
    end
  end
end
