# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oui < Formula
  desc "CLI tool for MAC Addresses."
  homepage "https://github.com/thatmattlove/oui"
  version "0.0.1"
  license "BSD-3-Clause-Clear"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thatmattlove/oui/releases/download/v0.0.1/oui_0.0.1_macOS_arm64.tar.gz"
      sha256 "7a00bea1a7ee19d9a7f8ebbda35f714b71cafd420df21e15af86717669cc0f78"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/oui/releases/download/v0.0.1/oui_0.0.1_macOS_amd64.tar.gz"
      sha256 "4864feca7868d1811a7a331e0104e60fcadf48b2ef3ae7e327edf4b03014904a"

      def install
        bin.install "oui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/oui/releases/download/v0.0.1/oui_0.0.1_linux_armv6.tar.gz"
      sha256 "199860b62f65b37aa52720add0c36cbcad82e9d25201b4b57cae99713112375c"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/oui/releases/download/v0.0.1/oui_0.0.1_linux_arm64.tar.gz"
      sha256 "50d9a9c5cb5ab30789d64afc16e4a89f0eb3aa0a47491243b3485e3900c08e83"

      def install
        bin.install "oui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/oui/releases/download/v0.0.1/oui_0.0.1_linux_amd64.tar.gz"
      sha256 "9c558145b5e34d4ce12d0a1db4e6e75d3329228e98ed4ddf1c98e2c1775f10f3"

      def install
        bin.install "oui"
      end
    end
  end

  def post_install
    system "oui", "update"

  end
end
