# This file was generated by GoReleaser. DO NOT EDIT.
cask "oui" do
  version "2.0.7"

  on_macos do
    on_intel do
      sha256 "74bb0673450be7debbc90e2d5688a783ec93f4e129d30f56742364750e396879"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92d39c8da20a3d6648fdefe75ad86f5c970e8c5a1172224baa106e2a2c414bd6"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97af22cec1e5cdaaed7a1fad5121f96277db7c5a9c146369e947aa9e9526d6ce"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4515ce4c6a626731b13f4aac532c680298575e2394610fdb35bd2e779c30b31b"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oui"
  desc "MAC Address CLI Toolkit"
  homepage "https://github.com/thatmattlove/oui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oui"

  # No zap stanza required

end
