# This file was generated by GoReleaser. DO NOT EDIT.
cask "oui" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "56aa61183dc14bdf707f582fa99e041e822a885f42d675892ba942723984ba79"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1bf806073c78048748959dc8d96d217114fd9eef29748fd5b7267ca0c919deb"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e81684553760870c76d2fbad5fe1b3b8868767fa779b23b6fc887814aebdf93b"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa45f81a4d5dc91e1efab0edf31a4a0e6da36fe7884a0461b79e1ed098c7bdd9"
      url "https://github.com/thatmattlove/oui/releases/download/v#{version}/oui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oui"
  desc "MAC Address CLI Toolkit"
  homepage "https://github.com/thatmattlove/oui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oui"

  # No zap stanza required

end
